ServerEvents.tags('fluid', event => {
    event.removeAll("ad_astra:tier_1_rocket_fuel")
    event.removeAll("ad_astra:tier_2_rocket_fuel")
    event.removeAll("ad_astra:tier_3_rocket_fuel")
    event.removeAll("ad_astra:tier_4_rocket_fuel")
    event.add('ad_astra:tier_1_rocket_fuel', 'mekanism_extras:rich_uranium_fuel')
    event.add('ad_astra:tier_2_rocket_fuel', 'mekanism_extras:fluorinated_naquadah_uranium_fuel')
    event.add('ad_astra:tier_2_rocket_fuel', 'mekanism_extras:fluorinated_naquadah_uranium_fuel')
    event.add('ad_astra:tier_2_rocket_fuel', 'anvilcraft:helium')
})