#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Oct 04 10:30:19 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.9.3.zip
